### ISSUE TITLE
Certain monsters on donjon.bin.sh break the book extraction logic

### ISSUE THREAD

**Issue by telboy007** [telboy007/donjon_to_homebrewery#34]
Following error:

Traceback (most recent call last):
  "completion_tokens": 322,
  File "convert_donjon_to_homebrewery.py", line 408, in <module>
  "prompt_tokens": 120,
    monster_name, sourcebook = extract_book_details(item, settings['ruleset'])
  File "/home/runner/work/donjon_to_homebrewery/donjon_to_homebrewery/dth/utilities/locations.py", line 101, in extract_book_details
    book = book_details[1].strip().replace(')','').replace(' ', ' p.')
IndexError: list index out of range

Caused by:

Vampire (warrior) - no monsters have had extra detail in brackets in previous runs of the dth tool.  Book extraction logic needs a simple change.

locations.py line 98
split = book_details.split('(')

Needs to split on cr rather than first bracket.

**Comment by telboy007** [comment]
Fixed
